Fix NullPointerException in getBuchungsZweckKorrektur
java.lang.NullPointerException: Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because "value" is null